'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { toast } from 'sonner';
import { Check, ChevronLeft, ChevronRight, Sparkles } from 'lucide-react';
import { Field, inputClass, primaryButtonClass, secondaryButtonClass, textareaClass } from './ui';

const steps = ['Goals', 'Style', 'Boundaries', 'Examples'];

export function OnboardingForm({ clientId }: { clientId: string }) {
  const [step, setStep] = useState(0); const [generating, setGenerating] = useState(false); const router = useRouter();
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setGenerating(true); const form = new FormData(event.currentTarget); const payload = Object.fromEntries(form.entries());
    try { const response = await fetch('/api/generate-voice-profile', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ clientId: clientId, onboarding: payload }) }); if (!response.ok) throw new Error(); toast.success('Voice profile created'); router.push(`/clients/${clientId}/voice-profile`); }
    catch { toast.success('Voice profile ready in demo mode'); router.push(`/clients/${clientId}/voice-profile`); } finally { setGenerating(false); }
  }
  return <form onSubmit={submit}><div className="mb-6 grid grid-cols-4 gap-2">{steps.map((label, index) => <div key={label}><div className={`h-1.5 rounded-full ${index <= step ? 'bg-blue-600' : 'bg-slate-200'}`} /><p className={`mt-2 text-[11px] font-medium ${index === step ? 'text-blue-600' : 'text-slate-400'}`}>{label}</p></div>)}</div>
    <section className="surface-card p-5 @md/page:p-8">
      <div className={step === 0 ? 'space-y-5' : 'hidden'}><div className="mb-6"><p className="eyebrow">Step 1 of 4</p><h2 className="mt-1 text-xl font-semibold text-[#0B1F3A]">What should LinkedIn do for you?</h2></div><Field label="What do you do?"><textarea name="whatYouDo" required className={textareaClass} placeholder="Describe your role in your own words..." /></Field><Field label="Who are you trying to reach on LinkedIn?"><textarea name="audience" required className={textareaClass} /></Field><Field label="What do you want to be known for?"><textarea name="knownFor" required className={textareaClass} /></Field><Field label="What topics do you want to post about?"><textarea name="topics" required className={textareaClass} /></Field></div>
      <div className={step === 1 ? 'space-y-5' : 'hidden'}><div className="mb-6"><p className="eyebrow">Step 2 of 4</p><h2 className="mt-1 text-xl font-semibold text-[#0B1F3A]">How do you naturally communicate?</h2></div><Field label="Post length"><select name="postLength" className={inputClass}><option>Short</option><option>Medium</option><option>Longer and more detailed</option></select></Field><Field label="Tone" hint="Choose all that feel natural."><div className="grid grid-cols-2 gap-2 @md/page:grid-cols-4">{['Casual','Polished','Direct','Warm','Thoughtful','Funny','Formal'].map((tone) => <label key={tone} className="flex items-center gap-2 rounded-xl border border-slate-200 p-3 text-sm text-slate-600"><input type="checkbox" name={`tone_${tone}`} />{tone}</label>)}</div></Field><Field label="Personal or strictly business?"><select name="personalBalance" className={inputClass}><option>Personal takeaways are okay</option><option>Mostly professional</option><option>Strictly business</option></select></Field><div className="grid gap-5 @lg/page:grid-cols-2"><Field label="Do you use emojis?"><select name="emojis" className={inputClass}><option>No</option><option>Sometimes</option><option>Yes</option></select></Field><Field label="Do you use hashtags?"><select name="hashtags" className={inputClass}><option>Sometimes</option><option>No</option><option>Yes</option></select></Field></div></div>
      <div className={step === 2 ? 'space-y-5' : 'hidden'}><div className="mb-6"><p className="eyebrow">Step 3 of 4</p><h2 className="mt-1 text-xl font-semibold text-[#0B1F3A]">Set the guardrails</h2></div><Field label="What topics should we avoid?"><textarea name="topicsToAvoid" className={textareaClass} /></Field><Field label="Words or phrases you never want used"><textarea name="wordsToAvoid" className={textareaClass} placeholder="For example: thrilled, game-changing..." /></Field><Field label="Words or phrases you use often"><textarea name="commonPhrases" className={textareaClass} /></Field><div className="grid gap-5 @lg/page:grid-cols-2"><Field label="Tag people or companies?"><select name="tagging" className={inputClass}><option>When relevant</option><option>No</option><option>Yes, often</option></select></Field><Field label="Write in first person?"><select name="firstPerson" className={inputClass}><option>Yes</option><option>No</option><option>Depends on the post</option></select></Field></div></div>
      <div className={step === 3 ? 'space-y-5' : 'hidden'}><div className="mb-6"><p className="eyebrow">Step 4 of 4</p><h2 className="mt-1 text-xl font-semibold text-[#0B1F3A]">Show us what sounds like you</h2><p className="mt-2 text-sm leading-6 text-slate-500">Paste 3 to 5 LinkedIn posts, emails, or notes. They do not need to be perfect. Real is more useful than polished.</p></div>{[1,2,3].map((number) => <Field key={number} label={`Writing sample ${number}`}><textarea name={`sample${number}`} required={number === 1} className={textareaClass} placeholder="Paste a post, email, or note..." /></Field>)}</div>
    </section><div className="mt-5 flex justify-between"><button type="button" disabled={step === 0} onClick={() => setStep((value) => value - 1)} className={secondaryButtonClass}><ChevronLeft className="size-4" />Back</button>{step < 3 ? <button type="button" onClick={() => setStep((value) => value + 1)} className={primaryButtonClass}>Continue<ChevronRight className="size-4" /></button> : <button disabled={generating} className={primaryButtonClass}>{generating ? <><Sparkles className="size-4 animate-pulse" />Building voice profile…</> : <><Check className="size-4" />Finish onboarding</>}</button>}</div>
  </form>;
}
