'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { ImagePlus, LoaderCircle, Sparkles, UploadCloud } from 'lucide-react';
import { toast } from 'sonner';
import { clients } from '@/lib/stay-visible/demo-data';
import { Field, inputClass, primaryButtonClass, secondaryButtonClass, textareaClass } from './ui';

const postTypes = ['Event Recap', 'Conference Post', 'Client Meeting', 'Market Insight', 'Company Repost', 'Article Share', 'Deal Announcement', 'General Update'];

export function PostOpportunityForm() {
  const [files, setFiles] = useState<string[]>([]); const [generating, setGenerating] = useState(false); const router = useRouter();
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setGenerating(true); const data = Object.fromEntries(new FormData(event.currentTarget).entries());
    try { const response = await fetch('/api/generate-linkedin-posts', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...data, photoContext: files.join(', ') }) }); if (!response.ok) throw new Error(); const json = await response.json(); sessionStorage.setItem('stayvisible-generated', JSON.stringify(json.options)); toast.success('Three post options are ready'); }
    catch { toast.success('Post options unavailable', { description: 'Add a client and OpenAI key for live generation.' }); }
    finally { setGenerating(false); router.push('/posts/generated/review'); }
  }
  return <form onSubmit={submit} className="grid gap-6 @4xl/page:grid-cols-[1.5fr_0.8fr]"><div className="space-y-6"><section className="surface-card p-5 @md/page:p-7"><div className="mb-6"><p className="eyebrow">The moment</p><h2 className="mt-1 font-semibold text-[#0B1F3A]">What happened?</h2></div><div className="grid gap-5 @lg/page:grid-cols-2"><Field label="Client"><select required name="clientId" className={inputClass}><option value="">Choose a client</option>{clients.filter((client) => client.status !== 'Paused').map((client) => <option key={client.id} value={client.id}>{client.firstName} {client.lastName}</option>)}</select></Field><Field label="Post type"><select required name="postType" className={inputClass}>{postTypes.map((type) => <option key={type}>{type}</option>)}</select></Field><Field label="Event or topic name"><input required name="topic" className={inputClass} placeholder="Event, meeting, article, or topic" /></Field><Field label="Date"><input type="date" name="date" className={inputClass} /></Field><Field label="Location"><input name="location" className={inputClass} placeholder="City, venue, or virtual" /></Field><Field label="People or companies to mention"><input name="mentions" className={inputClass} placeholder="Names or LinkedIn handles" /></Field></div><div className="mt-5 space-y-5"><Field label="Main takeaway"><textarea required name="mainTakeaway" className={textareaClass} placeholder="What was the one thing worth sharing?" /></Field><Field label="Notes"><textarea name="notes" className={textareaClass} placeholder="Messy notes are welcome. Add moments, quotes, or context..." /></Field></div></section>
      <section className="surface-card p-5 @md/page:p-7"><div className="mb-5 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-blue-50 text-blue-600"><ImagePlus className="size-5" /></span><div><h2 className="font-semibold text-[#0B1F3A]">Photos</h2><p className="text-sm text-slate-400">Optional, but often the best memory prompt.</p></div></div><label className="flex min-h-36 cursor-pointer flex-col items-center justify-center rounded-2xl border border-dashed border-blue-200 bg-blue-50/40 p-6 text-center transition hover:bg-blue-50"><UploadCloud className="size-6 text-blue-500" /><span className="mt-2 text-sm font-semibold text-blue-700">Choose photos</span><span className="mt-1 text-xs text-slate-400">JPG, PNG or WEBP · Up to 10 MB each</span><input type="file" multiple accept="image/*" className="sr-only" onChange={(event) => setFiles(Array.from(event.target.files ?? []).map((file) => file.name))} /></label>{files.length > 0 && <div className="mt-3 flex flex-wrap gap-2">{files.map((file) => <span key={file} className="rounded-lg bg-slate-100 px-3 py-1.5 text-xs text-slate-600">{file}</span>)}</div>}</section></div>
    <aside className="space-y-6"><section className="surface-card p-5 @md/page:p-6"><p className="eyebrow">Direction</p><h2 className="mt-1 font-semibold text-[#0B1F3A]">How should this one feel?</h2><div className="mt-5 space-y-5"><Field label="Desired tone"><select name="tone" className={inputClass}><option>Use client voice profile</option><option>More casual</option><option>More thoughtful</option><option>More direct</option><option>More professional</option></select></Field><Field label="Optional call to action"><textarea name="callToAction" className={textareaClass} placeholder="Leave blank if the post does not need one." /></Field></div></section><section className="rounded-2xl bg-[#0B1F3A] p-6 text-white"><Sparkles className="size-5 text-sky-300" /><h3 className="mt-4 font-semibold">You’ll get three directions</h3><ul className="mt-3 space-y-2 text-sm leading-6 text-slate-300"><li>Short and direct</li><li>Personal takeaway</li><li>Professional recap</li></ul><button disabled={generating} className={`${primaryButtonClass} mt-6 w-full bg-white text-[#0B1F3A] hover:bg-slate-100`}>{generating ? <><LoaderCircle className="size-4 animate-spin" />Writing options…</> : <><Sparkles className="size-4" />Generate 3 options</>}</button><button type="button" onClick={() => router.back()} className={`${secondaryButtonClass} mt-3 w-full border-white/15 bg-white/5 text-white hover:bg-white/10`}>Save as idea</button></section></aside></form>;
}
